"""
Source registry for the Springboard daily digest.

Each entry describes one monitored source.  Fields:
  id          – unique slug
  name        – display name
  source_type – governs article_type classification (see SOURCE_TYPE_MAP)
  rss_url     – feed URL, or None for scraped/manual sources
  has_rss     – True if this source is fetched via RSS
  scrape      – True if fetched by fetch_no_rss.py
  manual      – True if listed as "check manually" in the digest footer

article_type is derived at runtime from source_type:
  "policy"     -> Policy Development
  "discussion" -> Discussion
  "research"   -> Research & Reports
"""

SOURCE_TYPE_MAP = {
    "Federal government":  "policy",
    "P/T government":      "policy",
    "Intergovernmental":   "policy",
    "National news":       "discussion",
    "Regional news":       "discussion",
    "International news":  "discussion",
    "Advocacy":            "discussion",
    "Indigenous":          "discussion",
    "Think tank/research": "research",
    "Academic journal":    "research",
    "Individual":          "discussion",
}

SOURCES = [
    # ── Federal government (RSS) ──────────────────────────────────────────────
    {
        "id": "canada_gazette",
        "name": "Canada Gazette",
        "source_type": "Federal government",
        "rss_url": "https://gazette.gc.ca/rss/p1-eng.xml",
        "has_rss": True,
    },
    {
        "id": "canada_ca_news",
        "name": "Canada.ca News Releases",
        "source_type": "Federal government",
        "rss_url": "https://www.canada.ca/en/news.atom.xml",
        "has_rss": True,
    },
    {
        "id": "esdc",
        "name": "Employment and Social Development Canada",
        "source_type": "Federal government",
        "rss_url": "https://www.canada.ca/en/employment-social-development/news.atom.xml",
        "has_rss": True,
    },
    {
        "id": "national_defence",
        "name": "Department of National Defence",
        "source_type": "Federal government",
        "rss_url": "https://www.canada.ca/en/department-national-defence/news.atom.xml",
        "has_rss": True,
    },
    {
        "id": "transport_canada",
        "name": "Transport Canada",
        "source_type": "Federal government",
        "rss_url": "https://www.canada.ca/en/transport-canada/news.atom.xml",
        "has_rss": True,
    },
    {
        "id": "global_affairs",
        "name": "Global Affairs Canada",
        "source_type": "Federal government",
        "rss_url": "https://www.canada.ca/en/global-affairs/news.atom.xml",
        "has_rss": True,
    },
    {
        "id": "auditor_general",
        "name": "Auditor General of Canada",
        "source_type": "Federal government",
        "rss_url": "https://www.oag-bvg.gc.ca/internet/English/oag-bvg_rss_e_23439.xml",
        "verify_ssl": False,
        "has_rss": True,
    },
    {
        "id": "pbo",
        "name": "Parliamentary Budget Officer",
        "source_type": "Federal government",
        "rss_url": "https://www.pbo-dpb.ca/api/publications?format=atom",
        "has_rss": True,
    },
    {
        "id": "statcan",
        "name": "Statistics Canada — The Daily",
        "source_type": "Federal government",
        "rss_url": "https://www150.statcan.gc.ca/n1/rss/daily-quotidien-eng.xml",
        "has_rss": True,
    },
    # ── P/T government (RSS) ──────────────────────────────────────────────────
    {
        "id": "yukon_govt",
        "name": "Yukon Government",
        "source_type": "P/T government",
        "rss_url": "https://yukon.ca/en/rss.xml",
        "has_rss": True,
    },
    {
        "id": "nwt_govt",
        "name": "Northwest Territories Government",
        "source_type": "P/T government",
        "rss_url": "https://www.gov.nt.ca/en/newsroom/feed",
        "has_rss": True,
    },
    {
        "id": "ontario_newsroom",
        "name": "Ontario Newsroom",
        "source_type": "P/T government",
        "rss_url": "https://news.ontario.ca/en/feed",
        "has_rss": True,
    },
    {
        "id": "bc_newsroom",
        "name": "BC Government Newsroom",
        "source_type": "P/T government",
        "rss_url": "https://news.gov.bc.ca/feed",
        "has_rss": True,
    },
    {
        "id": "alberta_govt",
        "name": "Alberta Government News",
        "source_type": "P/T government",
        "rss_url": "https://www.alberta.ca/news/rss",
        "has_rss": True,
    },
    {
        "id": "quebec_govt",
        "name": "Quebec Government News",
        "source_type": "P/T government",
        "rss_url": "https://www.newswire.ca/rss/public-affairs/quebec-government.rss",
        "has_rss": True,
    },
    {
        "id": "manitoba_govt",
        "name": "Manitoba Government News",
        "source_type": "P/T government",
        "rss_url": "https://news.gov.mb.ca/news/rss/index.html",
        "has_rss": True,
    },
    {
        "id": "saskatchewan_govt",
        "name": "Saskatchewan Government News",
        "source_type": "P/T government",
        "rss_url": "https://www.saskatchewan.ca/government/news-and-media/rss",
        "has_rss": True,
    },
    {
        "id": "nova_scotia_govt",
        "name": "Nova Scotia Government News",
        "source_type": "P/T government",
        "rss_url": "https://novascotia.ca/news/rss/",
        "has_rss": True,
    },
    {
        "id": "new_brunswick_govt",
        "name": "New Brunswick Government News",
        "source_type": "P/T government",
        "rss_url": "https://www2.gnb.ca/content/gnb/en/news/rss.html",
        "has_rss": True,
    },
    {
        "id": "pei_govt",
        "name": "PEI Government News",
        "source_type": "P/T government",
        "rss_url": "https://www.princeedwardisland.ca/en/information/executive-council-office/news-releases-rss",
        "has_rss": True,
    },
    {
        "id": "newfoundland_govt",
        "name": "Newfoundland & Labrador Government News",
        "source_type": "P/T government",
        "rss_url": "https://www.releases.gov.nl.ca/releases/rss/index.asp",
        "has_rss": True,
    },
    # ── National news (RSS) ───────────────────────────────────────────────────
    {
        "id": "cbc_news",
        "name": "CBC News",
        "source_type": "National news",
        "rss_url": "https://rss.cbc.ca/lineup/topstories.xml",
        "has_rss": True,
    },
    {
        "id": "cbc_north",
        "name": "CBC North",
        "source_type": "Regional news",
        "rss_url": "https://rss.cbc.ca/lineup/canada-north.xml",
        "has_rss": True,
    },
    {
        "id": "toronto_star",
        "name": "Toronto Star",
        "source_type": "National news",
        "rss_url": "https://www.thestar.com/content/thestar/feed.rss",
        "has_rss": True,
    },
    {
        "id": "globe_mail",
        "name": "The Globe and Mail",
        "source_type": "National news",
        "rss_url": "https://www.theglobeandmail.com/arc/outboundfeeds/rss/category/canada/",
        "has_rss": True,
        "paywalled": True,
    },
    {
        "id": "national_post",
        "name": "National Post",
        "source_type": "National news",
        "rss_url": "https://nationalpost.com/feed/",
        "has_rss": True,
    },
    {
        "id": "ipolitics",
        "name": "iPolitics",
        "source_type": "National news",
        "rss_url": "https://ipolitics.ca/feed/",
        "has_rss": True,
        "paywalled": True,
    },
    {
        "id": "hill_times",
        "name": "The Hill Times",
        "source_type": "National news",
        "rss_url": "https://www.hilltimes.com/feed/",
        "has_rss": True,
        "paywalled": True,
    },
    {
        "id": "macleans",
        "name": "Maclean's",
        "source_type": "National news",
        "rss_url": "https://macleans.ca/feed/",
        "has_rss": True,
    },
    {
        "id": "canadian_press",
        "name": "The Canadian Press",
        "source_type": "National news",
        "rss_url": "https://www.thecanadianpress.com/feed/",
        "has_rss": True,
    },
    {
        "id": "ccpa",
        "name": "CCPA (Canadian Centre for Policy Alternatives)",
        "source_type": "Think tank/research",
        "rss_url": "https://policyalternatives.ca/feed/",
        "has_rss": True,
    },
    {
        "id": "montreal_gazette",
        "name": "Montreal Gazette",
        "source_type": "National news",
        "rss_url": "https://montrealgazette.com/feed",
        "has_rss": True,
    },
    {
        "id": "the_tyee",
        "name": "The Tyee",
        "source_type": "National news",
        "rss_url": "https://thetyee.ca/rss2.xml",
        "has_rss": True,
    },
    {
        "id": "rabble",
        "name": "Rabble",
        "source_type": "National news",
        "rss_url": "https://rabble.ca/feed/",
        "has_rss": True,
    },
    {
        "id": "reuters_canada",
        "name": "Reuters Canada",
        "source_type": "National news",
        "rss_url": "https://feeds.reuters.com/reuters/CATopNews",
        "has_rss": True,
    },
    # ── Regional / specialist news (RSS) ──────────────────────────────────────
    {
        "id": "nunatsiaq",
        "name": "Nunatsiaq News",
        "source_type": "Regional news",
        "rss_url": "https://nunatsiaqonline.ca/feed/",
        "has_rss": True,
    },
    {
        "id": "high_north_news",
        "name": "High North News",
        "source_type": "International news",
        "rss_url": "https://www.highnorthnews.com/en/rss.xml",
        "has_rss": True,
    },
    {
        "id": "arctic_today",
        "name": "Arctic Today",
        "source_type": "International news",
        "rss_url": "https://www.arctictoday.com/feed/",
        "has_rss": True,
    },
    {
        "id": "the_narwhal",
        "name": "The Narwhal",
        "source_type": "National news",
        "rss_url": "https://thenarwhal.ca/feed/",
        "has_rss": True,
    },
    # ── Think tanks / research (RSS) ──────────────────────────────────────────
    {
        "id": "policy_options",
        "name": "Policy Options (IRPP)",
        "source_type": "Think tank/research",
        "rss_url": "https://policyoptions.irpp.org/feed/",
        "has_rss": True,
    },
    {
        "id": "cd_howe",
        "name": "C.D. Howe Institute",
        "source_type": "Think tank/research",
        "rss_url": "https://cdhowe.org/feed/",
        "has_rss": True,
    },
    {
        "id": "conference_board",
        "name": "Conference Board of Canada",
        "source_type": "Think tank/research",
        "rss_url": "https://www.conferenceboard.ca/feed/",
        "has_rss": True,
    },
    {
        "id": "future_skills_centre",
        "name": "Future Skills Centre",
        "source_type": "Think tank/research",
        "rss_url": "https://fsc-ccf.ca/feed/",
        "has_rss": True,
    },
    {
        "id": "lmic",
        "name": "Labour Market Information Council (LMIC)",
        "source_type": "Think tank/research",
        "rss_url": "https://lmic-cimt.ca/feed/",
        "has_rss": True,
    },
    {
        "id": "brookfield",
        "name": "Brookfield Institute",
        "source_type": "Think tank/research",
        "rss_url": "https://brookfieldinstitute.ca/feed/",
        "has_rss": True,
    },
    {
        "id": "atlantic_council",
        "name": "Atlantic Council",
        "source_type": "Think tank/research",
        "rss_url": "https://www.atlanticcouncil.org/feed/",
        "has_rss": True,
    },
    {
        "id": "arctic_institute",
        "name": "Arctic Institute of North America",
        "source_type": "Think tank/research",
        "rss_url": "https://arctic.ucalgary.ca/rss.xml",
        "has_rss": True,
    },
    {
        "id": "maytree",
        "name": "Maytree Foundation",
        "source_type": "Think tank/research",
        "rss_url": "https://maytree.com/feed/",
        "has_rss": True,
    },
    {
        "id": "wellesley",
        "name": "Wellesley Institute",
        "source_type": "Think tank/research",
        "rss_url": "https://www.wellesleyinstitute.com/feed/",
        "has_rss": True,
    },
    {
        "id": "colleges_institutes",
        "name": "Colleges & Institutes Canada",
        "source_type": "Think tank/research",
        "rss_url": "https://www.collegesinstitutes.ca/feed/",
        "has_rss": True,
    },
    # ── Advocacy (RSS) ────────────────────────────────────────────────────────
    {
        "id": "campaign2000",
        "name": "Campaign 2000",
        "source_type": "Advocacy",
        "rss_url": "https://campaign2000.ca/feed/",
        "has_rss": True,
    },
    {
        "id": "basic_income_canada",
        "name": "Basic Income Canada Network",
        "source_type": "Advocacy",
        "rss_url": "https://www.basicincomecanada.org/feed/",
        "has_rss": True,
    },
    # ── Indigenous organizations (RSS) ────────────────────────────────────────
    {
        "id": "afn",
        "name": "Assembly of First Nations",
        "source_type": "Indigenous",
        "rss_url": "https://afn.ca/feed/",
        "has_rss": True,
    },
    {
        "id": "itk",
        "name": "Inuit Tapiriit Kanatami (ITK)",
        "source_type": "Indigenous",
        "rss_url": "https://www.itk.ca/feed/",
        "has_rss": True,
    },
    {
        "id": "nti",
        "name": "Nunavut Tunngavik Inc. (NTI)",
        "source_type": "Indigenous",
        "rss_url": "https://www.tunngavik.com/feed/",
        "has_rss": True,
    },
    {
        "id": "metis_national",
        "name": "Métis National Council",
        "source_type": "Indigenous",
        "rss_url": "https://www.metisnation.ca/feed/",
        "has_rss": True,
    },
    {
        "id": "nwac",
        "name": "Native Women's Association of Canada",
        "source_type": "Indigenous",
        "rss_url": "https://www.nwac.ca/feed/",
        "has_rss": True,
    },
    # ── Intergovernmental (RSS) ───────────────────────────────────────────────
    {
        "id": "arctic_council",
        "name": "Arctic Council",
        "source_type": "Intergovernmental",
        "rss_url": "https://arctic-council.org/en/feed/",
        "has_rss": True,
    },
    {
        "id": "oecd_skills",
        "name": "OECD — Skills",
        "source_type": "Intergovernmental",
        "rss_url": "https://www.oecd.org/en/topics/skills.xml",
        "has_rss": True,
    },
    {
        "id": "oecd_social",
        "name": "OECD — Social Policy",
        "source_type": "Intergovernmental",
        "rss_url": "https://www.oecd.org/en/topics/social-policy.xml",
        "has_rss": True,
    },
    {
        "id": "ilo",
        "name": "International Labour Organization",
        "source_type": "Intergovernmental",
        "rss_url": "https://www.ilo.org/rss/en",
        "has_rss": True,
    },
    # ── Academic journals (RSS) ───────────────────────────────────────────────
    {
        "id": "cpp_journal",
        "name": "Canadian Public Policy Journal",
        "source_type": "Academic journal",
        "rss_url": "https://utpjournals.press/action/showFeed?type=etoc&feed=rss&jc=cpp",
        "has_rss": True,
    },
    {
        "id": "arctic_journal",
        "name": "Arctic Journal (AINA)",
        "source_type": "Academic journal",
        "rss_url": "https://arcticjournal.com/feed/",
        "has_rss": True,
    },
    # ── Scraped sources (no RSS) ──────────────────────────────────────────────
    {
        "id": "hoc",
        "name": "House of Commons Committees",
        "source_type": "Federal government",
        "rss_url": None,
        "has_rss": False,
        "scrape": True,
        "scrape_module": "fetch_hoc",
    },
    {
        "id": "senate",
        "name": "Senate of Canada Committees",
        "source_type": "Federal government",
        "rss_url": None,
        "has_rss": False,
        "scrape": True,
        "scrape_module": "fetch_senate",
    },
    {
        "id": "cannor",
        "name": "CanNor (Canadian Northern Economic Development Agency)",
        "source_type": "Federal government",
        "rss_url": None,
        "has_rss": False,
        "scrape": True,
        "news_url": "https://www.cannor.gc.ca/eng/1362495730541/1362495898070",
    },
    {
        "id": "nunavut_housing",
        "name": "Nunavut Housing Corporation",
        "source_type": "P/T government",
        "rss_url": None,
        "has_rss": False,
        "scrape": True,
        "news_url": "https://www.nunavuthousing.ca/news/",
    },
    {
        "id": "nunavut_govt",
        "name": "Government of Nunavut",
        "source_type": "P/T government",
        "rss_url": None,
        "has_rss": False,
        "scrape": True,
        "news_url": "https://www.gov.nu.ca/en/news",
    },
    {
        "id": "norad",
        "name": "NORAD",
        "source_type": "Intergovernmental",
        "rss_url": None,
        "has_rss": False,
        "scrape": True,
        "news_url": "https://www.norad.mil/Media/News/",
    },
    {
        "id": "inuvialuit",
        "name": "Inuvialuit Regional Corporation",
        "source_type": "Indigenous",
        "rss_url": None,
        "has_rss": False,
        "scrape": True,
        "wordpress": True,
        "base_url": "https://www.irc.inuvialuit.com",
        "news_url": "https://www.irc.inuvialuit.com/news",
    },
    {
        "id": "makivik",
        "name": "Makivik Corporation",
        "source_type": "Indigenous",
        "rss_url": None,
        "has_rss": False,
        "scrape": True,
        "news_url": "https://www.makivik.org/category/news/",
    },
    {
        "id": "nunatsiavut",
        "name": "Nunatsiavut Government",
        "source_type": "Indigenous",
        "rss_url": None,
        "has_rss": False,
        "scrape": True,
        "wordpress": True,
        "base_url": "https://www.nunatsiavut.com",
        "news_url": "https://www.nunatsiavut.com/media/news/",
    },
    {
        "id": "dehcho",
        "name": "Dehcho First Nations",
        "source_type": "Indigenous",
        "rss_url": None,
        "has_rss": False,
        "scrape": True,
        "wordpress": True,
        "base_url": "https://www.dehcho.org",
        "news_url": "https://www.dehcho.org/news/",
    },
    {
        "id": "cap",
        "name": "Congress of Aboriginal Peoples",
        "source_type": "Indigenous",
        "rss_url": None,
        "has_rss": False,
        "scrape": True,
        "wordpress": True,
        "base_url": "https://abo-peoples.org",
        "news_url": "https://abo-peoples.org/news/",
    },
    # ── Manual-check sources (no RSS, no scraper) ─────────────────────────────
    {
        "id": "cipser",
        "name": "CIPSER / Carleton University",
        "source_type": "Think tank/research",
        "rss_url": None,
        "has_rss": False,
        "scrape": False,
        "manual": True,
        "url": "https://carleton.ca/cipser",
    },
    {
        "id": "diversity_institute",
        "name": "Diversity Institute (Toronto Metropolitan University)",
        "source_type": "Think tank/research",
        "rss_url": None,
        "has_rss": False,
        "scrape": False,
        "manual": True,
        "url": "https://www.diversityinstitute.ca",
    },
    {
        "id": "crsp",
        "name": "Canadian Review of Social Policy",
        "source_type": "Academic journal",
        "rss_url": None,
        "has_rss": False,
        "scrape": False,
        "manual": True,
        "url": "https://crsp.journals.yorku.ca",
    },
    {
        "id": "bc_workforce",
        "name": "WorkBC",
        "source_type": "P/T government",
        "rss_url": None,
        "has_rss": False,
        "scrape": False,
        "manual": True,
        "url": "https://www.workbc.ca",
    },
]
